'use strict';
const fs=require('fs'),http=require('http'),path=require('path');
const HOST='127.0.0.1',PORT=Number(process.env.PORT)||3001,PUBLIC_DIR=path.join(__dirname,'public'),DATA_DIR=path.join(__dirname,'data'),LOG_FILE=path.join(DATA_DIR,'keyboard-events.jsonl'),MAX_BODY=64*1024;
const ALLOWED_TYPES=new Set(['keydown','keyup']),MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};
function ensureLog(){fs.mkdirSync(DATA_DIR,{recursive:true,mode:0o700});if(!fs.existsSync(LOG_FILE))fs.writeFileSync(LOG_FILE,'',{mode:0o600})}
function sendJson(response,status,value){response.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});response.end(JSON.stringify(value))}
function validateEvent(value){return Boolean(value&&ALLOWED_TYPES.has(value.type)&&typeof value.key==='string'&&value.key.length>0&&value.key.length<=32&&Number.isFinite(value.timestamp))}
function readBody(request){return new Promise((resolve,reject)=>{let body='';request.on('data',chunk=>{body+=chunk;if(Buffer.byteLength(body)>MAX_BODY)reject(new Error('Request is too large.'))});request.on('end',()=>resolve(body));request.on('error',reject)})}
async function api(request,response,url){ensureLog();if(request.method==='POST'&&url.pathname==='/api/events'){try{const parsed=JSON.parse(await readBody(request));if(!Array.isArray(parsed.events)||parsed.events.length>100||!parsed.events.every(validateEvent))return sendJson(response,400,{error:'Invalid event batch.'});const lines=parsed.events.map(event=>JSON.stringify({timestamp:new Date(event.timestamp).toISOString(),type:event.type,key:event.key})).join('\n');if(lines)fs.appendFileSync(LOG_FILE,`${lines}\n`,{encoding:'utf8',mode:0o600});return sendJson(response,201,{saved:parsed.events.length})}catch(error){return sendJson(response,400,{error:error.message})}}if(request.method==='GET'&&url.pathname==='/api/events'){const lines=fs.readFileSync(LOG_FILE,'utf8').trim().split('\n').filter(Boolean).slice(-500);return sendJson(response,200,{events:lines.map(line=>JSON.parse(line))})}if(request.method==='DELETE'&&url.pathname==='/api/events'){fs.writeFileSync(LOG_FILE,'',{mode:0o600});return sendJson(response,200,{cleared:true})}return false}
function staticFile(request,response,url){if(request.method!=='GET')return response.writeHead(405).end('Method not allowed');const requested=url.pathname==='/'?'/index.html':url.pathname,target=path.resolve(PUBLIC_DIR,`.${requested}`);if(!target.startsWith(`${PUBLIC_DIR}${path.sep}`))return response.writeHead(403).end('Forbidden');fs.readFile(target,(error,data)=>{if(error)return response.writeHead(error.code==='ENOENT'?404:500).end('Not found');response.writeHead(200,{'Content-Type':MIME[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'"});response.end(data)})}
const server=http.createServer(async(request,response)=>{const url=new URL(request.url,`http://${HOST}:${PORT}`);if(url.pathname.startsWith('/api/')){const handled=await api(request,response,url);if(handled===false)sendJson(response,404,{error:'Not found.'});return}staticFile(request,response,url)});
if(require.main===module)server.listen(PORT,HOST,()=>console.log(`ConsentKey is running at http://${HOST}:${PORT}`));
module.exports={server,validateEvent};
